architecture: srcnn
batch_size: 32
num_workers_train: 0
num_workers_valid: 0


shuffle: True
patches: _patches192

dataset_parameters:
  data_path: C:\data
  bicubic_down: True
  bicubic_up: True
  extension: png
  scaling_factors: [2]

model_parameters:
  feature_maps_gen: 192
  feature_maps_disc: 192
  scale_factor: 2
