architecture: srcnn
batch_size: 32
num_workers_train: 0
num_workers_valid: 0

shuffle: True
patches: _patches192

dataset_parameters:
  data_path: C:\data
  bicubic_down: True
  bicubic_up: True
  extension: png
  scaling_factors: [4]

model_parameters:
  augment_train: false
  loss: L1
  perceptual_loss: True

